# Generated by Django 5.0.3 on 2024-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
